name: Build and Publish storybook to GitHub Pages
run-name: ${{ github.actor }} is deploying to gh pages! 🚀
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    name: "Release storybook preview ⚛"
    runs-on: ubuntu-latest
    steps:
      - name: "allow github actions to use this repo code"
        uses: actions/checkout@v4
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Enable pnpm
        run: corepack enable
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: pnpm i
          build_command: pnpm build-storybook
          path: storybook-static
