name: Build and Publish storybook to GitHub Pages
run-name: ${{ github.actor }} is deploying to gh pages! 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    name: "Release storybook preview ⚛"
    runs-on: ubuntu-latest
    steps:
      - name: "allow github actions to use this repo code"
        uses: actions/checkout@v4
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Enable pnpm
        run: corepack enable
      - name: build storybook
        run: pnpm build-storybook
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./storybook-static"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
