name: Automated test of the ui library
run-name: ${{ github.actor }} is testing the ui library 🧪
on:
  push:
    branches:
      - master
jobs:
  testing:
    name: "Testing my library component library 🧪"
    runs-on: ubuntu-latest
    steps:
      - name: "allow github actions to use this repo code"
        uses: actions/checkout@v4
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm i
      - run: pnpm test
